### ISSUE TITLE
not loading expect splash screen

### ISSUE THREAD

**Issue by manioxx** [ikhsan3adi/quick_social#2]

**Comment by manioxx** [comment]
it doesnt load to the home page it only load to splash screen nothing more tha that

**Comment by ikhsan3adi** [comment]
Can you provide detailed information?

**Comment by manioxx** [comment]
i only show the quicksocial nothing much after that it stuck there but just now i fixed it some how but now showing object event progress and and here isnt a login screen or what and its loading the previous data
![Screenshot 2024-06-13 074453](https://github.com/ikhsan3adi/quick_social/assets/144020769/37b3ea62-126a-4431-9219-cc2a18cd4a38)
